#!/bin/zsh
#
# Retrieve chip (processor) information.
#

HW_INFO=$(system_profiler SPHardwareDataType 2>/dev/null)

# awk to pattern match `Chip`
# sub to strip everything up to and including the colon and space
# e.g.: Chip: Apple A18 Pro
chip() {
    awk '/Chip:/{ sub(/.*: /, ""); print; }' <<< "$HW_INFO"
}

chip
