#!/bin/zsh
#
# Retrieve processor information.
#

HW_INFO=$(system_profiler SPHardwareDataType 2>/dev/null)

# awk to extract string, strip string to right of: 'Chip:'

processor() {
    awk '/Chip:/{ sub(/^.*: /, ""); print; }' <<< "$HW_INFO"
}

processor
