#!/usr/bin/env bash
# 
# Extract masOS system version information 

# Extract field 1 from macOS software version number,
# assign field to variable,
# run a number check, and display corresponding marketing name.

RELEASE_NAME=(
["11"]="Big Sur"
["12"]="Monterey"
["13"]="Ventura"
["14"]="Sonoma"
["15"]="Sequoia"
["26"]="Tahoe"
)

# Parse 'short' product version and assign to variable.

parse_version() {
  long_version=$(sw_vers -productVersion)
  short_version=$(printf "%s" "$long_version" |awk -F '.' '{ print $1 }')
}

# If $short_version in table, assign macOS_name to corresponding marketing name.

macOS_release_name() {
  if [[ -n "${RELEASE_NAME[$short_version]}" ]]; then
    macOS_release_name=${RELEASE_NAME[$short_version]}
  fi
}

macOS_version() { 
  printf "%s\n" "$macOS_release_name $long_version"
}

# Wrapper function.
macOS_name_wrapper() {
  parse_version
  macOS_release_name
  macOS_version
}

macOS_name_wrapper "$@"
