#!/usr/bin/env zsh
#
# macOS marketing name and full version number.
# 
 
# Lookup table.

declare -A RELEASE_NAME=(
["11"]="Big Sur"
["12"]="Monterey"
["13"]="Ventura"
["14"]="Sonoma"
["15"]="Sequoia"
["26"]="Tahoe"
)

# Use `sw_vers` to extract product version, e.g.:
# full_version: 26.4.1
# major_version: 26

parse_version() {
  full_version=$(sw_vers -productVersion)
  major_version=$(printf "%s" "$full_version" |awk -F '.' '{ print $1 }')
}

# If major_version is in lookup table,
# assign corresponding marketing name to macOS_name.

macOS_name() {
  if [[ -n "${RELEASE_NAME[$major_version]}" ]]; then
    macOS_name=${RELEASE_NAME[$major_version]}
  fi
}

# Print macOS marketing name and full version number.

macOS_version() { 
  printf "%s\n" "$macOS_name $full_version"
}

# Wrapper function.

macOS_name_wrapper() {
  parse_version
  macOS_name
  macOS_version
}

macOS_name_wrapper "$@"
