#!/bin/zsh
#
# macOS marketing name and full version number.
#

OS_INFO=$(sw_vers -productVersion)

# Use `sw_vers` to extract product version, e.g.:
# full_version: 26.4.
# major_version: 26 (awk field separator . and print first field
full_version=$OS_INFO
major_version=$(awk -F '.' '{print $1}' <<< "$OS_INFO")
 
# Lookup table
declare -A RELEASE_NAME=(
["11"]="Big Sur"
["12"]="Monterey"
["13"]="Ventura"
["14"]="Sonoma"
["15"]="Sequoia"
["26"]="Tahoe"
)

macOS_name() {
  printf "%s\\n" "${RELEASE_NAME[$major_version]} $full_version"
}

macOS_name
