#!/bin/zsh
#
# Extract RAM info.
#

HW_INFO=$(system_profiler SPHardwareDataType 2>/dev/null)

# awk to pattern match GB
# print size and unit
# e.g.: Memory: 8 GB
memory() {
  awk '/GB/ {print $2, $3}' <<< "$HW_INFO"
}

memory
