#!/bin/zsh
#
# Retrieve model name.
#

# awk to pattern match `Model Name` 
# sub to strip everything up to and including the colon and space

model_name() {
  local modname
  modname=$(system_profiler SPHardwareDataType \
    | awk '/Model Name/ {sub(/.*: /, ""); print}') 
  printf "%s\n" "${modname}"
} 

model_name
