#!/bin/zsh
#
# Retrieve processor information.
#

# awk to extract string, strip string to right of: 'Chip:' 

processor() {
  local cpu
  cpu=$(system_profiler SPHardwareDataType \
    | awk '/Chip:/{ sub(/^.*: /, ""); print; }')
  printf "%s\\n" "${cpu}"
}

processor

# Extended CPU info can be parsed with this:
# awk '/Chip/ || /Cores/ { sub(/^.*: /, ""); print; }'\
