#!/bin/zsh
#
# Retrieve serial number.
#

# awk to pattern match `Serial` and print last field of that string.

serial_number() {
  local serialnum
  serialnum=$(system_profiler SPHardwareDataType | awk '/Serial/ {print $NF}')
  printf "%s\n" "${serialnum}"
} 

serial_number
