#!/bin/zsh
#
# Retrieve startup disk information
#

# awk to match indendeted section headers ending in ":"
# print stored name when startup volume is identified by mount point

startup_disk() {
  system_profiler SPStorageDataType |
  awk '/^[[:space:]]+[^[:space:]].*:$/ {
         sub(/^[[:space:]]+/, "")
         sub(/:$/, "")
         n=$0
       }
       /Mount Point: \/$/ {print n; exit}'
}

startup_disk
