#!/bin/zsh

startup_disk
#!/usr/bin/env bash
# Retrieve startup disk information

startup_disk() {
  system_profiler SPStorageDataType |
  awk '/^[[:space:]]+[^[:space:]].*:$/ {
         sub(/^[[:space:]]+/, "")
         sub(/:$/, "")
         n=$0
       }
       /Mount Point: \/$/ {print n; exit}'
}

startup_disk
