#!/bin/zsh
#
# Print a label/value pair.
#

# Right-justify label in 20-character field, followed by value
# e.g.: 
#       Sample label: Sample value
write_header() {
  printf "%20s: %s\n" "$1" "$2"
}

write_header "Sample label" "Sample value"
