#!/bin/bash
#
# Detect system architecture (Apple Silicon, x86_64).
#

architecture() { 
  if [[ $(uname -m) == 'arm64' ]]; then
    printf "%s\n" "Apple Silicon architecture"
  elif [[ $(uname -m) == 'x86_64' ]]; then
    printf "%s\n" "Intel architecture"
  else 
    printf "%s\n" "Unable to detect system architecture."
fi
}

architecture
