#!/bin/bash
#
# Convert Apple’s version number into internal “release number,"
# then look that up in release name and print.
# e.g.:
# sw_vers -productVersion
# 14.7.5
# field_1=14
# field_2=7
# field_3=5
# Since 14 > 10:
# macOS_release_number=$((14 + 5))
# RELEASE_NAME[19]="Sonoma"
#
# Works for macOS 10.x & 11+
# 

# Lookup table
RELEASE_NAME=(
["10"]="Yosemite"
["11"]="El Capitan"
["12"]="Sierra"
["13"]="High Sierra"
["14"]="Mojave"
["15"]="Catalina"
["16"]="Big Sur"
["17"]="Monterey"
["18"]="Ventura"
["19"]="Sonoma"
["20"]="Sequoia"
)

# Parse fields 1, 2, 3 and assign to eponymous variables.
parse_version() {
  IFS=. read -r field_1 field_2 field_3 < <(sw_vers -productVersion)
}

# If field_1 greater than 10, add five (5) to variable
# else use field_2.
get_macOS_release_number() {
  if [[ "$field_1" -gt 10 ]]; then
    macOS_release_number=$((field_1 + 5))
  else
    macOS_release_number=$((field_2))
  fi
}

# If macOS_release_number in array, 
# assign macOS_release_name to corresponding marketing name.
get_macOS_release_name() {
  if [[ -n "${RELEASE_NAME[$macOS_release_number]}" ]]; then
    macOS_release_name=${RELEASE_NAME[$macOS_release_number]}
fi
    printf "%s\n" "macOS" "$macOS_release_name"
}

# Wrapper.
main() {
  parse_version
  get_macOS_release_number
  get_macOS_release_name
}

main "$@"
