#!/usr/bin/env bash
# Notes: Post-macOS 11.x.x. Intel, Apple Silicon chips.

# Extract fields 1 and 2 from macOS software version number,
# assign those fields to variables,
# run a number check, and display corresponding marketing name.

# Lookup table

RELEASE_NAME=(

["10"]="Yosemite"
["11"]="El Capitan"
["12"]="Sierra"
["13"]="High Sierra"
["14"]="Mojave"
["15"]="Catalina"
["16"]="Big Sur"
["17"]="Monterey"
["18"]="Ventura"
["19"]="Sonoma"
)

# Parse field 1, field 2, and assign to eponymous variables.

parse_version() {

  IFS=. read -r field_1 field_2 field_3 < <(sw_vers -productVersion)
}

# If field_1 greater than 10, add five (5) to variable
# else use field_2.

macOS_release_number() {

  if [[ "$field_1" -gt 10 ]]; then
    macOS_release_number=$((field_1 + 5))
  else
    macOS_release_number=$((field_2))
  fi
}

# If macOS_release_number in array, assign macOS_release_name to corresponding marketing name.

macOS_release_name() {

  if [[ -n "${RELEASE_NAME[$macOS_release_number]}" ]]; then
    macOS_release_name=${RELEASE_NAME[$macOS_release_number]}
fi
    printf "%s\n" "macOS" "$macOS_release_name"
}

# Wrapper.

main() {
  parse_version
  macOS_release_number
  macOS_release_name
}

main "$@"
