#!/usr/bin/env bash
#
# Retrieve serial number.
#

# system_profiler --> awk to extract `Serial` row -->
# print field 4 
serial_number() {
  local serialnum
  serialnum=$(system_profiler SPHardwareDataType | awk '/Serial/ {print $4}')
  printf "%s\n" "${serialnum}"
} 

serial_number
