#!/usr/bin/env bash
# Funtion to take values and print header.

write_header() {

  local name=$1; shift;

  printf "%s\\n""--------------------\\n$name%s\\n--------------------\\n"
  printf "%s\\n" "$@"
}

write_header "Sample Header" "Sample Output"
