#!/usr/bin/env bash
#
# aboutMeAppleSilicon
#
# CLI alternative to the macOS "About This Mac" (Apple Silicon)
#
# Author: M. Krinitz <mjk235 [at] nyu [dot] edu>
# Date: 2022.07.25
# License: MIT

RELEASE_NAME=(
  ["11"]="Big Sur"
  ["12"]="Monterey"
  ["13"]="Ventura"
  ["14"]="Sonoma"
  ["15"]="Sequoia"
)

write_header() {
  local name=$1; shift;
  printf "%s\n""--------------------\n$name%s\n--------------------\n"
  printf "%s\n" "$@"
}

check_architecture() {
  if [[ $(uname -m) != 'arm64' ]]; then
    printf "%s\n" "This version of aboutMeAppleSilicon is intended for Apple Silicon Macs."
    exit 1
  fi
}

parse_version() {
  short_version=$(sw_vers -productVersion | awk -F '.' '{ print $1 }')
}

get_macOS_release_name() {
  if [[ -n "${RELEASE_NAME[$short_version]}" ]]; then
    macOS_release_name=${RELEASE_NAME[$short_version]}
  fi

  write_header "macOS" "$macOS_release_name"
}

macOS_name_wrapper() {
  parse_version
  get_macOS_release_name
}

macOS_version() {
  local long_version

  long_version=$(sw_vers -productVersion)

  write_header "Version" "$long_version"
}

hardware_model() {
  local hardware_mod

  hardware_mod=$(defaults read ~/Library/Preferences/com.apple.SystemProfiler.plist 'CPU Names' \
    | sed -E '/=/!d; s/.*= "//; s/".*//;')

  write_header "Hardware Model" "$hardware_mod"
}

processor() {
  local cpu

  cpu=$(system_profiler SPHardwareDataType \
    | awk '/Chip:/ { sub(/^.*: /, ""); print; }')

  write_header "Chip" "$cpu"
}

memory() {
  local ram

  ram=$(
    awk '
      $1~/Memory/ && $2!~/Empty/ {size+=$2}
      END {print size " GB"}
    ' <<< "$(system_profiler SPMemoryDataType)"
  )

  write_header "Memory" "$ram"
}

startup_disk() {
  local disk

  disk=$(
    system_profiler SPStorageDataType |
      awk '
        /^[[:space:]]+[^[:space:]].*:$/ {
          sub(/^[[:space:]]+/, "")
          sub(/:$/, "")
          disk = $0
        }

        /Mount Point: \/$/ {
          print disk
          exit
        }
      '
  )

  write_header "Startup Disk" "$disk"
}

serial_number() {
  local serialnum

  serialnum=$(system_profiler SPHardwareDataType | awk '/Serial/ {print $4}')

  write_header "Serial Number" "$serialnum"
}

main() {
  check_architecture
  macOS_name_wrapper
  macOS_version
  hardware_model
  processor
  memory
  startup_disk
  serial_number
}

main "$@"
