#!/bin/bash
#
# aboutMeIntel 
#
# CLI alternative to the macOS "About this Mac" feature.
#
# Author: M. Krinitz <mjk235 [at] nyu [dot] edu>
# Date: 2021.04.22
# License: MIT

# Lookup table.
RELEASE_NAME=(
  ["10"]="Yosemite"
  ["11"]="El Capitan"
  ["12"]="Sierra"
  ["13"]="High Sierra"
  ["14"]="Mojave"
  ["15"]="Catalina"
  ["16"]="Big Sur"
  ["17"]="Monterey"
  ["18"]="Ventura"
  ["19"]="Sonoma"
  ["20"]="Sequoia"
)

write_header() {
  local name=$1; shift;
  printf "%s\n""--------------------\n$name%s\n--------------------\n"
  printf "%s\n" "$@"
}

check_architecture() {
  if [[ $(uname -m) != 'x86_64' ]]; then
    printf "%s\n" "This version of aboutMe is intended for Intel-based Macs."
    exit 1
  fi
}

parse_version() {
  IFS=. read -r field_1 field_2 field_3 < <(sw_vers -productVersion)
}

get_macOS_release_number() {
  if [[ "$field_1" -gt 10 ]]; then
    macOS_release_number=$((field_1 + 5))
  else
    macOS_release_number=$((field_2))
  fi
}

get_macOS_release_name() {
  if [[ -n "${RELEASE_NAME[$macOS_release_number]}" ]]; then
    macOS_release_name=${RELEASE_NAME[$macOS_release_number]}
  fi

  write_header "macOS" "$macOS_release_name"
}

macOS_release_name_wrapper() {
  parse_version
  get_macOS_release_number
  get_macOS_release_name
}

macOS_version() {
  local long_version

  long_version=$(sw_vers -productVersion)

  write_header "Version" "$long_version"
}

hardware_model() {
  local hardware_mod

  hardware_mod=$(defaults read ~/Library/Preferences/com.apple.SystemProfiler.plist 'CPU Names' \
    | sed -E '/=/!d; s/.*= "//; s/".*//;')

  write_header "Hardware Model" "$hardware_mod"
}

processor() {
  local cpu

  cpu=$(system_profiler SPHardwareDataType \
    | awk '/Processor (Name|Speed):/ { sub(/^.*: /, ""); print; }' \
    | sort \
    | xargs)

  write_header "Processor" "$cpu"
}

memory() {
  local ram

  ram=$(
    awk '
      $1~/Size/ && $2!~/Empty/ {size+=$2}
      $1~/Speed/ && $2!~/Empty/ {speed=$2" "$3}
      $1~/Type/ && $2!~/Empty/ {type=$2}
      END {print size " GB " speed " " type}
    ' <<< "$(system_profiler SPMemoryDataType)"
  )

  write_header "Memory" "$ram"
}

startup_disk() {
  local disk

  disk=$(
    system_profiler SPStorageDataType |
      awk '
        /^[[:space:]]+[^[:space:]].*:$/ {
          sub(/^[[:space:]]+/, "")
          sub(/:$/, "")
          disk = $0
        }

        /Mount Point: \/$/ {
          print disk
          exit
        }
      '
  )

  write_header "Startup Disk" "$disk"
}

graphics() {
  local gpu

  gpu=$(system_profiler SPDisplaysDataType 2>/dev/null \
    | awk '/(Model|Max\)|Total\)):/ { sub(/^.*: /, ""); print; }' \
    | xargs)

  write_header "Graphics" "$gpu"
}

serial_number() {
  local serialnum

  serialnum=$(system_profiler SPHardwareDataType | awk '/Serial/ {print $4}')

  write_header "Serial Number" "$serialnum"
}

main() {
  check_architecture
  macOS_release_name_wrapper
  macOS_version
  architecture
  hardware_model
  processor
  memory
  startup_disk
  graphics
  serial_number
}

main "$@"
