#!/usr/local/bin/env bash
# Alt approach to retrieve hardware_model contained in 'functions' directory.
# Use if preference list from other function is not present.

hardware_model_too () {
  local hardware_model

  hardware_model=$(system_profiler SPHardwareDataType \
    | awk '/Model Identifier:/{ sub(/^.*: /, ""); print; }')

  printf "%s\\n" "${hardware_model}"

} 

hardware_model_too
