#!/usr/bin/env bash
# Retrieve startup disk information
# awk to extract third field
# sed to print string to the right of ':'
#
# Retrieve mount point information 
# awk to extract 'Mount Point'
# head to get primary drive

startup_disk_too () {
  
  local disk mount

  disk=$(system_profiler SPStorageDataType |awk 'FNR == 3 {print}'|sed 's/[[:blank:]:]*//g')

  mount=$(system_profiler SPStorageDataType \
    |awk '/Mount Point/ { sub(/^.*: /, ""); print; }' |head -1)

  printf "%s\\n" "${disk}"
  printf "%s\\n" "${mount}"
}

startup_disk_too
