#!bin/zsh
#
# aboutMe (Apple Silicon)
#
# CLI alternative to the macOS "About this Mac" feature.
#
# Author: M. Krinitz <mjk235 [at] nyu [dot] edu>
# Date: 2026.05.02
# License: MIT

# System profiler
OS_INFO=$(sw_vers -productVersion)

# Disk profiler
DISK_INFO=$(system_profiler SPStorageDataType)

# Lookup table
declare -A RELEASE_NAME=(
["11"]="Big Sur"
["12"]="Monterey"
["13"]="Ventura"
["14"]="Sonoma"
["15"]="Sequoia"
["26"]="Tahoe"
)

# Display header message
write_header() {
  local name=$1; shift;
  printf "--------------------\n%s\n--------------------\n" "$name"
  printf "%s\n" "$@"
}

# Model name
model_name() {
  awk '/Model Name/ {sub(/.*: /, ""); print}' <<< "$HW_INFO"
}

# Chip name
chip() {
    awk '/Chip:/{ sub(/.*: /, ""); print; }' <<< "$HW_INFO"
}

# Memory
memory() {
  awk '/GB/ {print $2, $3}' <<< "$HW_INFO"
}

# Startup disk
startup_disk() {
  awk '
    /^[[:space:]]+[^[:space:]].*:$/ {
      sub(/^[[:space:]]+/, "")
      sub(/:$/, "")
      n=$0
    }
    /Mount Point: \/$/ {print n; exit}
  ' <<< "$DISK_INFO"
}

# Serial number
serial_number() {
  awk '/Serial Number/ {print $NF}' <<< "$HW_INFO"
}

# macOS name
macOS_name() {
  printf "%s\n" "${RELEASE_NAME[$major_version]} $full_version"
}

# Architecture wrapper (Intel, Apple Silicon).

Intel_wrapper() {

  release_name_wrapper
  macOS_version
  hardware_model
  Intel_processor
  Intel_memory
  startup_disk
  graphics
  serial_number
}

Apple_silicon_wrapper() {

  release_name_wrapper
  macOS_version
  hardware_model
  apple_silicon_processor
  apple_silicon_memory
  startup_disk
  serial_number
}

# Las entranas del programa.

main() {

  if [[ $(uname -m) == 'arm64' ]]; then
    Apple_silicon_wrapper

  elif [[ $(uname -m) == 'x86_64' ]]; then
    Intel_wrapper

  else
    printf "%s\n" "Unable to detect system architecture. Exiting."
fi
}

main "$@"
