#!/bin/zsh
#
# aboutMe (Apple Silicon)
#
# CLI alternative to the macOS "About this Mac" feature.
#
# Author: M. Krinitz <mjk235 [at] nyu [dot] edu>
# Date: 2026.05.02
# License: MIT

# Hardware profiler
HW_INFO=$(system_profiler SPHardwareDataType 2>/dev/null)
# Disk profiler
DISK_INFO=$(system_profiler SPStorageDataType)
# OS version
OS_INFO=$(sw_vers -productVersion)
full_version=$OS_INFO
major_version=$(awk -F '.' '{print $1}' <<< "$OS_INFO")

# Lookup table
declare -A RELEASE_NAME=(
["11"]="Big Sur"
["12"]="Monterey"
["13"]="Ventura"
["14"]="Sonoma"
["15"]="Sequoia"
["26"]="Tahoe"
)

# Display header message
write_header() {
  local name=$1; shift;
  printf "--------------------\n%s\n--------------------\n" "$name"
  printf "%s\n" "$@"
}

# Model name
model_name() {
  awk '/Model Name/ {sub(/.*: /, ""); print}' <<< "$HW_INFO"
}

# Chip name
chip() {
    awk '/Chip:/{ sub(/.*: /, ""); print; }' <<< "$HW_INFO"
}

# Memory
memory() {
  awk '/GB/ {print $2, $3}' <<< "$HW_INFO"
}

# Startup disk
startup_disk() {
  awk '
    /^[[:space:]]+[^[:space:]].*:$/ {
      sub(/^[[:space:]]+/, "")
      sub(/:$/, "")
      n=$0
    }
    /Mount Point: \/$/ {print n; exit}
  ' <<< "$DISK_INFO"
}

# Serial number
serial_number() {
  awk '/Serial Number/ {print $NF}' <<< "$HW_INFO"
}

# macOS name
macOS_name() {
  printf "%s\n" "${RELEASE_NAME[$major_version]} $full_version"
}

# Las entranas del programa.
main() {
  write_header "Model Name" "$(model_name)"
  write_header "Chip" "$(chip)"
  write_header "Memory" "$(memory)"
  write_header "Serial Number" "$(serial_number)"
  write_header "Startup Disk" "$(startup_disk)"
  write_header "macOS" "$(macOS_name)"
}

main "$@"
